#! /bin/sh -
#
# Evaluate numbers of reftest skipped on a specific platform
#

readonly ALL_PLATFORMS=( window mac b2g android )
readonly ALL_CONDITIONS=( "skip-if" "random-if" "fail-if" )
PLATFOMRS=( )
# by default, gather all skip-if test cases
CONDITIONS=( skip-if )

help_message()
{
  echo "Help TODO"
  exit 0
}

# $1 - positional parameter
# $2 - valid values
# $3 - output valid values
function parse_parameter_value
{
  declare -a params=(${1//:/ })
  declare -a alls=("${!2}")
  #platforms=(`echo $1 | cut -d ':' -f  1-`)

  # verify platforms
  for i in "${params[@]}"
  do
    local found=0
    for j in "${alls[@]}"
    do
      if [ "${i}" == "${j}" ]; then
        found=1
        break
      fi
    done

    if [ "${found}" -eq "0" ]; then
      echo "Error - invalidate parameter: $i"
      exit 1
    fi
  done

  eval "$3=( "${params[@]}" )"
}

# position parameter parsing
while test $# -gt 0
do
  case $1 in
    --help | -h | '-?' )
      help_message
      ;;
    --platform | -p)
      d=`echo $2 | sed -n "/^-/!p"`
      if [ "${#d}" -ne "0" ]; then
        parse_parameter_value $2 ALL_PLATFORMS[@] PLATFORMS
        shift
      fi
      ;;
    --condition | -c)
      d=`echo $2 | sed -n "/^-/!p"`
      if [ "${#d}" -ne "0" ]; then
        parse_parameter_value $2 ALL_CONDITIONS[@] CONDITIONS
        shift
      fi
      ;;
    -* )
      echo "Unrecognized option: $1"
      exit 1
      ;;
    * )
      break
      ;;
  esac
  shift
done

echo "Platforms = "${PLATFORMS[@]}""
echo "Conditions = "${CONDITIONS[@]}""

# OK, input parameters seem to be correct.
# The platfroms that we are interested on are stored in PLATFORMS
# The conditions that we are interested on are stored in CONDITIONS

# Gather XXXX.list files
FILES=( $(find . -name reftest.list) )

for file in "${FILES[@]}"
do
  echo "`sed -n "/#/!p" "$file" |
         sed -n "/skip-if([!)]*B2G.*)/p"`\
  "
  echo "--------------"
done
